Write runtime and mem usage to user-defined files

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,5 +1,14 @@
 #!/bin/bash
 
+# max time before benchmark program gets killed
+max_runtime_sec=3600
+
+# interval in which memory consumption is recorded
+mem_poll_interval_ms=50
+
+# maximum number of trials before a run gets aborted
+max_trials=3
+
 # configure this for your system
 classpath="/opt/local/share/scala-2.10/lib/scala-library.jar:/opt/local/share/scala-2.10/lib/akka-actors.jar:/opt/local/share/scala-2.10/lib/typesafe-config.jar"
 
@@ -7,12 +16,14 @@ classpath="/opt/local/share/scala-2.10/lib/scala-library.jar:/opt/local/share/sc
 classpath_foundry="actor_foundry/lib_src/lib/foundry-1.0.jar:actor_foundry/lib_src/classes"
 
 usage="\
-usage: $0 USERID BIN_PATH IMPL BENCH
+usage: $0 USERID BIN_PATH IMPL BENCH RUNTIME_FILE MEM_USAGE_FILE
 
-  USERID:   ID of the user the benchmark should run (script needs root access)
-  BIN_PATH: path to CAF binaries
-  IMPL:     (caf|scala|erlang|foundry)
-  BENCH:    (mixed_case|actor_creation|mailbox_performance)
+  USERID:         ID of the user this benchmark should run as
+  BIN_PATH:       path to CAF binaries
+  RUNTIME_FILE:   output file for runtime
+  MEM_USAGE_FILE: output file for memory consumption
+  IMPL:           (caf|scala|erlang|foundry)
+  BENCH:          (mixed_case|actor_creation|mailbox_performance)
 
 "
 
@@ -33,15 +44,12 @@ else
 fi
 
 cmd=""
-username="$1"
-userid=$(id -u $username)
-shift
-binpath="$1"
-shift
-impl="$1"
-shift
-bench="$1"
-shift
+username="$1" ; userid=$(id -u $username) ; shift
+binpath="$1" ; shift
+runtime_out_file="$1" ; shift
+mem_usage_out_file="$1" ; shift
+impl="$1" ; shift
+bench="$1" ; shift
 
 java_cmd=$(which java)
 erl_cmd=$(which erl)
@@ -69,5 +77,11 @@ esac
 olddir=$PWD
 cd "$binpath"
 export JAVA_OPTS="-Xmx40960M"
-./caf_run_bench $userid 3600 75 $cmd
-cd "$olddir"
+for trial in $(seq 1 $max_trials); do
+  if ./caf_run_bench $userid $max_runtime_sec $mem_poll_interval_ms "$runtime_out_file" "$mem_usage_out_file" $cmd ; then
+    cd "$olddir"
+    exit 0
+  fi
+done
+
+echo "benchmark did fail $max_trials times, abort" 1>&2
